export const STATES = {
  STARTMODE: '_STARTMODE', // Prompt the user to start or restart the game.
  NAMEMODE: '_NAMEMODE',
  RIVALMODE: '_RIVALMODE',
  MOVEMENTMODE: '_MOVEMENTMODE',
  CHOOSELOCATIONMODE: '_CHOOSELOCATIONMODE',
  CHOOSEPOKEMONMODE: '_CHOOSEPOKEMONMODE',
  BATTLEMODE: '_BATTLEMODE',
  BATTLEOVERMODE: '_BATTLEOVERMODE',
  CHOOSEMOVEMODE: '_CHOOSEMOVEMODE',
  SWITCHPOKEMODE: '_SWITCHPOKEMODE',
  BAGMODE: '_BAGMODE',
  WHITEOUTMODE: '_WHITEOUTMODE',
  POKECENTERMODE: '_POKECENTERMODE',
  POKEMARTMODE: '_POKEMARTMODE',
  CITYMODE: '_CITYMODE',
  ASKMODE: '_ASKMODE', // Alexa is asking user the questions.
  DESCRIPTIONMODE: '_DESCRIPTIONMODE', // Alexa is describing the final choice and prompting to start again or quit
} as const;
